services:

  # https://medium.com/swlh/alpine-slim-stretch-buster-jessie-bullseye-bookworm-what-are-the-differences-in-docker-62171ed4531d
  # https://dev.to/bgord/multiple-postgres-databases-in-a-single-docker-container-417l

  justdrink-database:
    image: postgres:15.2
    volumes:
      - ../_database/db-data:/var/lib/postgresql/data/
      - ../_database/sql:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    networks:
      - justdrink
    ports:
      - "10010:5432"

  pgadmin:
    image: dpage/pgadmin4:7.0
    env_file:
      - ./database.dev.env
    networks:
      - justdrink
    ports:
      - "10020:80"

  justdrink-keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: start-dev
    depends_on:
      justdrink-database:
        condition: service_completed_successfully
    env_file:
      - ./keycloak.dev.env
    ports:
      - "8080:8080"
      - "8787:8787"
    networks:
      - justdrink

  backoffice-service:
    image: luzzetti/backoffice-bootloader:latest
    ports:
      - "9090:8080"
    networks:
      - justdrink
    mem_limit: 500m

  backoffice-ui-vue:
    image: luzzetti/backoffice-ui-vue:latest
    ports:
      - "7070:80"
    networks:
      - justdrink
    mem_limit: 50mb

networks:
  justdrink:
    name: justdrink
    driver: bridge
