services:

  backoffice-service:
    image: luzzetti/backoffice-bootloader:0.0.2-SNAPSHOT
    ports:
      - "9090:8080"
    networks:
      - justdrink
    mem_limit: 500m

#   backoffice-ui-vue:
#     image: luzzetti/backoffice-ui-vue:latest
#     ports:
#       - "7070:80"
#     networks:
#       - justdrink
#     mem_limit: 50mb

networks:
  justdrink:
    name: justdrink
    driver: bridge
