server:
  port: 8080

spring:
  application:
    name: backoffice

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10010/backoffice

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
    hibernate:
      ddl-auto: none

  # OVVIAMENTE...vanno configurati per prod. E i valori iniettati dall'esterno (Env?)
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test-client
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/justdrink
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/justdrink
