server:
  port: 8080

spring:
  application:
    name: backoffice


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10010/backoffice

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
    hibernate:
      ddl-auto: none