server:
  port: 9090


spring:

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  datasource:
    username: DATABASE_USERNAME
    password: DATABASE_PASSWORD

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    it:
      luzzetti:
        justdrink:
          backoffice: DEBUG
