server:
  port: 9090

spring:

  datasource:
    username: justdrink_usr
    password: justdrink_pwd

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none # NON CAMBIARE!!! Utilizzare Liquibase

  liquibase:
    drop-first: true
    enabled: true


logging:
  level:
    org:
      hibernate:
        envers:
          boot: warn
      springframework:
        security: debug
    it:
      luzzetti:
        justdrink:
          backoffice: DEBUG
    liquibase: info
