server:
  port: 8080

spring:
  application:
    name: backoffice

  # These OBVIOUSLY aren't the production passwords.
  # These are injected, once the system will be hardened
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_GENERATION}
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # OVVIAMENTE...vanno configurati per prod. E i valori iniettati dall'esterno (Env?)
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: test-client
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
            user-name-attribute: preferred_username

      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

logging:
  level:
    org.springframework.security: debug
    it:
      luzzetti:
        justdrink:
          backoffice: DEBUG
