-- liquibase formatted sql

-- changeset chris:1685991181562-1
CREATE TABLE CUISINE
(
    RESTAURANT_ID BYTEA NOT NULL,
    name          VARCHAR(255)
);

-- changeset chris:1685991181562-2
CREATE TABLE DELIVERY_AREAS
(
    ID      BYTEA NOT NULL,
    polygon GEOMETRY,
    CONSTRAINT DELIVERY_AREASPK PRIMARY KEY (ID)
);

-- changeset chris:1685991181562-3
CREATE TABLE MENUS
(
    id            BYTEA NOT NULL,
    RESTAURANT_ID BYTEA,
    CONSTRAINT MENUSPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-4
CREATE TABLE OPENINGS
(
    id          BYTEA NOT NULL,
    "closeTime" time WITHOUT TIME ZONE,
    "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE,
    "dayOfWeek" SMALLINT,
    "openTime"  time WITHOUT TIME ZONE,
    WORKTIME_ID BYTEA,
    CONSTRAINT OPENINGSPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-5
CREATE TABLE OVERRULES
(
    id                     BYTEA NOT NULL,
    "alternativeCloseTime" time WITHOUT TIME ZONE,
    "alternativeOpenTime"  time WITHOUT TIME ZONE,
    closed                 BOOLEAN,
    "createdAt"            TIMESTAMP(6) WITHOUT TIME ZONE,
    "dayOfWeek"            SMALLINT,
    "validFrom"            date,
    "validThrough"         date,
    WORKTIME_ID            BYTEA,
    CONSTRAINT OVERRULESPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-6
CREATE TABLE PRODUCTS
(
    id          BYTEA NOT NULL,
    "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE,
    name        VARCHAR(255),
    price       numeric(38, 2),
    SECTION_ID  BYTEA,
    CONSTRAINT PRODUCTSPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-7
CREATE TABLE RESTAURANTS
(
    id                 BYTEA        NOT NULL,
    addressDisplayName VARCHAR(255) NOT NULL,
    addressLatitude    FLOAT(53)    NOT NULL,
    addressLongitude   FLOAT(53)    NOT NULL,
    enabled            BOOLEAN      NOT NULL,
    "logoPath"         VARCHAR(255),
    name               VARCHAR(255) NOT NULL,
    ownerEmail         VARCHAR(255) NOT NULL,
    owner_id           BYTEA        NOT NULL,
    ownerUsername      VARCHAR(255) NOT NULL,
    CONSTRAINT RESTAURANTSPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-8
CREATE TABLE SECTIONS
(
    id          BYTEA NOT NULL,
    "createdAt" TIMESTAMP(6) WITHOUT TIME ZONE,
    title       VARCHAR(255),
    MENU_ID     BYTEA,
    CONSTRAINT SECTIONSPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-9
CREATE TABLE WORKTIMES
(
    id            BYTEA NOT NULL,
    RESTAURANT_ID BYTEA,
    CONSTRAINT WORKTIMESPK PRIMARY KEY (id)
);

-- changeset chris:1685991181562-10
ALTER TABLE OVERRULES
    ADD CONSTRAINT "FK_OVERRULE_TO_WORKTIME" FOREIGN KEY (WORKTIME_ID) REFERENCES WORKTIMES (id);

-- changeset chris:1685991181562-11
ALTER TABLE OPENINGS
    ADD CONSTRAINT "FK_OPENING_TO_WORKTIME" FOREIGN KEY (WORKTIME_ID) REFERENCES WORKTIMES (id);

-- changeset chris:1685991181562-12
ALTER TABLE WORKTIMES
    ADD CONSTRAINT "FK_WORKTIME_TO_RESTAURANT" FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (id);

-- changeset chris:1685991181562-13
ALTER TABLE PRODUCTS
    ADD CONSTRAINT "FK_PRODUCT_TO_SECTION" FOREIGN KEY (SECTION_ID) REFERENCES SECTIONS (id);

-- changeset chris:1685991181562-14
ALTER TABLE SECTIONS
    ADD CONSTRAINT "FK_SECTION_TO_MENU" FOREIGN KEY (MENU_ID) REFERENCES MENUS (id);

-- changeset chris:1685991181562-15
ALTER TABLE DELIVERY_AREAS
    ADD CONSTRAINT "FK_DELIVERY_AREA_TO_RESTAURANT" FOREIGN KEY (ID) REFERENCES RESTAURANTS (id);

-- changeset chris:1685991181562-16
ALTER TABLE MENUS
    ADD CONSTRAINT "FK_MENU_TO_RESTAURANT" FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (id);

-- changeset chris:1685991181562-17
ALTER TABLE CUISINE
    ADD CONSTRAINT "FK_CUISINE_TO_RESTAURANT" FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (id);
