name: Builda e Spingi

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: Buildo con Maven
      run: mvn clean install -f ./backoffice-service/pom.xml
      
    - name: Creo il container con spring-boot
      run: mvn spring-boot:build-image -f ./backoffice-service/backoffice-bootloader/pom.xml
